# BERT分类器配置

# 模型配置
model:
  name: 'log_classifier'
  pretrained_model_name: 'bert-base-uncased'
  num_labels: 5
  max_length: 128

# 数据配置
data:
  train_path: 'data/logs_train.csv'
  val_split: 0.2
  balance_dataset: true
  max_class_ratio: 3.0

# 训练配置
training:
  seed: 42
  batch_size: 32
  num_workers: 4
  learning_rate: 2.0e-5
  max_epochs: 10
  early_stop_patience: 3
  gradient_clip_val: 1.0
  checkpoint_dir: 'checkpoints/'
  log_dir: 'logs/'
  model_dir: 'models/' 